//! Cross-implementation conformance for the Vela Sidon Producer Profile v1.
//!
//! The Rust canonical/packet layer (`vela_protocol::sidon_profile`) must agree
//! with the Python reference (`research/sidon-producer-profile/reference/`)
//! byte for byte. The landed fixtures were generated by the Python reference;
//! here the Rust port recomputes every packet ID from the packet body and
//! verifies every Ed25519 signature over the domain-separated preimage. If the
//! canonical JSON encoding, the content-id scheme, or the signing preimage
//! diverged from Python by a single byte, the recomputed IDs or the signature
//! checks would fail. This is the bedrock the later roots commit to.

use std::collections::BTreeSet;
use std::path::PathBuf;

use serde_json::Value;
use vela_protocol::sidon_profile::{packet_body, packet_id, prefix_for, verify_signed_packet};

fn load(name: &str) -> Value {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../research/sidon-producer-profile/fixtures")
        .join(name);
    let text =
        std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    serde_json::from_str(&text).unwrap_or_else(|e| panic!("parse {}: {e}", path.display()))
}

/// Every packet in the comprehensive loop fixture: its ID recomputes to the
/// Python-generated value, and its signature verifies under the Rust port.
#[test]
fn loop_fixture_every_packet_id_and_signature_agrees() {
    let fx = load("sidon-root-pinned-loop.json");
    let packets = fx["packets"].as_array().expect("packets array");
    assert!(!packets.is_empty(), "fixture carries no packets");

    let mut ids = BTreeSet::new();
    let mut types = BTreeSet::new();
    for (i, packet) in packets.iter().enumerate() {
        let ptype = packet["packet_type"]
            .as_str()
            .unwrap_or_else(|| panic!("packet {i} missing packet_type"));
        let stored = packet["packet_id"]
            .as_str()
            .unwrap_or_else(|| panic!("packet {i} ({ptype}) missing packet_id"));

        // (1) Recompute the ID over the body. Equality proves the canonical
        // JSON subset + content-id scheme agree with Python byte for byte over
        // the real, deeply nested packet bodies (observations embed every root).
        let body = packet_body(packet);
        let recomputed =
            packet_id(ptype, &body).unwrap_or_else(|e| panic!("packet {i} ({ptype}) id: {e}"));
        assert_eq!(
            recomputed, stored,
            "packet {i} ({ptype}) recomputed id diverges from Python"
        );

        // (2) Full verify: ID match + Ed25519 over SIGNATURE_DOMAIN||id||0||body.
        // Passing proves the signing preimage agrees with Python too.
        let verified = verify_signed_packet(packet)
            .unwrap_or_else(|e| panic!("packet {i} ({ptype}) verify: {e}"));
        assert_eq!(verified, stored);

        assert!(ids.insert(stored.to_string()), "duplicate packet id at {i}");
        types.insert(ptype.to_string());
    }

    // The loop fixture exercises all nine profile packet types.
    let expected_types: BTreeSet<String> = [
        "observation",
        "task",
        "result",
        "gate_receipt",
        "acceptance",
        "support_function",
        "challenge",
        "view_decision",
        "repair",
    ]
    .iter()
    .map(|s| (*s).to_string())
    .collect();
    assert_eq!(
        types, expected_types,
        "loop fixture must exercise all nine packet types"
    );
    assert!(prefix_for("observation").is_some());

    // The packets the fixture's `expected` block names by ID all resolve to
    // verified packets.
    for key in [
        "challenge_packet_id",
        "view_decision_packet_id",
        "repair_packet_id",
    ] {
        let id = fx["expected"][key]
            .as_str()
            .unwrap_or_else(|| panic!("fixture expected.{key} absent"));
        assert!(
            ids.contains(id),
            "expected.{key}={id} is not among the verified packets"
        );
    }
}

/// Tampering with a real fixture packet's body must break verification — proof
/// the conformance check is not vacuously passing.
#[test]
fn tampering_a_real_packet_breaks_verification() {
    let fx = load("sidon-root-pinned-loop.json");
    let packets = fx["packets"].as_array().unwrap();
    let mut packet = packets
        .iter()
        .find(|p| p["packet_type"].as_str() == Some("observation"))
        .expect("an observation packet")
        .clone();

    // Original verifies.
    assert!(verify_signed_packet(&packet).is_ok());

    // Flip the schema version: the recomputed ID no longer matches the stored
    // one (and the schema-version guard also fires).
    packet["schema_version"] = Value::from("vela.sidon-producer-profile.TAMPERED");
    assert!(verify_signed_packet(&packet).is_err());
}
