//! Export/render handlers (preprint, OEIS, nanopub), split out of cli.rs.
use crate::cli::{collect_witness_files, fail, fail_return, parse_witness, print_json};
use serde_json::json;
use std::path::{Path, PathBuf};
use vela_protocol::cli_style as style;
use vela_protocol::repo;

/// v0.163: handle `vela preprint <frontier>`. Renders a Markdown
/// preprint body for the frontier.
pub(crate) fn cmd_preprint(
    frontier: PathBuf,
    released_at: Option<String>,
    out: Option<PathBuf>,
    json: bool,
) {
    use vela_edge::preprint::render_preprint;

    let project = repo::load_from_path(&frontier).unwrap_or_else(|e| fail_return(&e));
    let stamp = released_at.unwrap_or_else(|| chrono::Utc::now().to_rfc3339());
    let body = render_preprint(&project, &stamp);

    if let Some(out_path) = out {
        std::fs::write(&out_path, &body)
            .unwrap_or_else(|e| fail_return(&format!("write {}: {e}", out_path.display())));
        if json {
            let payload = json!({
                "ok": true,
                "command": "preprint",
                "frontier_id": project.frontier_id(),
                "released_at": stamp,
                "bytes": body.len(),
                "out": out_path.display().to_string(),
            });
            print_json(&payload);
        } else {
            println!(
                "{} preprint for {} -> {} ({} bytes)",
                style::ok("preprint"),
                project.frontier_id(),
                out_path.display(),
                body.len()
            );
        }
    } else {
        println!("{body}");
    }
}

/// `vela reproduce` — re-verify stored witnesses from scratch with the
/// frozen exact verifiers. Trust is never self-reported.
/// Venue export, OEIS shape: project sidon witnesses into the exact
/// comment + b-file form the A309370 adoptions used. Rides the existing
/// registry's subsidy; the witness repo URL is the %H line.
pub(crate) fn cmd_export_oeis(path: &Path, sequence: &str) {
    let files = collect_witness_files(path);
    let mut rows: Vec<(usize, usize)> = Vec::new();
    for file in &files {
        let Ok(raw) = std::fs::read_to_string(file) else {
            continue;
        };
        let Ok(w) = parse_witness(&raw) else { continue };
        if let vela_verify::Witness::Sidon { n, points, .. } = &w {
            let r = vela_verify::verify_witness(&w);
            if r.ok {
                rows.push((*n, points.len()));
            }
        }
    }
    if rows.is_empty() {
        fail(&format!(
            "no verified sidon witnesses under {} — venue oeis currently projects sidon sets only",
            path.display()
        ));
    }
    rows.sort();
    rows.dedup();
    println!("%% OEIS {sequence} update material (generated by `vela export --venue oeis`)");
    println!("%% Every value below is backed by an explicit witness re-verified by a frozen");
    println!("%% deterministic checker. Witnesses + verifier:");
    println!(
        "%H {sequence} W. Blair, <a href=\"https://github.com/willblair0708/verified-combinatorics\">Verified witnesses and verification script</a>"
    );
    for (n, size) in &rows {
        println!(
            "%% a({n}) >= {size}  [witness verified: {size} points, all pairwise sums distinct]"
        );
    }
    println!("%% b-file fragment (lower bounds):");
    for (n, size) in &rows {
        println!("{n} {size}");
    }
}

/// Venue export, nanopub shape: one TriG document per verified finding
/// with a verifier attachment — assertion graph carries the claim,
/// provenance carries the verifier + witness hash + replay command,
/// pubinfo carries the signing key. Pure projection of signed state.
pub(crate) fn cmd_export_nanopub(path: &Path) {
    let project = repo::load_from_path(path).unwrap_or_else(|e| fail_return(&e));
    let mut emitted = 0usize;
    for f in &project.findings {
        let atts: Vec<_> = project
            .verifier_attachments
            .iter()
            .filter(|a| a.target == f.id && format!("{:?}", a.outcome).contains("Passed"))
            .collect();
        let attestations: Vec<_> = project
            .statement_attestations
            .iter()
            .filter(|a| a.target == f.id)
            .collect();
        // Emit only for findings carrying machine receipts (passing
        // attachments) or signed human judgment (statement attestations)
        // — a nanopub with neither would be assertion-only noise.
        if atts.is_empty() && attestations.is_empty() {
            continue;
        }
        let np = format!("http://purl.org/vela/np/{}", f.id);
        println!("@prefix np: <http://www.nanopub.org/nschema#> .");
        println!("@prefix prov: <http://www.w3.org/ns/prov#> .");
        println!("@prefix vela: <http://purl.org/vela/ns#> .");
        println!();
        println!("<{np}#head> {{");
        println!("  <{np}> a np:Nanopublication ;");
        println!("    np:hasAssertion <{np}#assertion> ;");
        println!("    np:hasProvenance <{np}#provenance> ;");
        println!("    np:hasPublicationInfo <{np}#pubinfo> .");
        println!("}}");
        println!("<{np}#assertion> {{");
        println!(
            "  <{np}#claim> vela:assertionText {} .",
            serde_json::to_string(&f.assertion.text).unwrap_or_default()
        );
        println!("}}");
        println!("<{np}#provenance> {{");
        for at in &attestations {
            println!(
                "  <{np}#claim> vela:statementAttestation [ vela:verdict {:?} ; vela:attestedBy {:?} ; vela:attestationId {:?} ] .",
                format!("{:?}", at.verdict).to_lowercase(),
                at.attested_by,
                at.id
            );
        }
        for a in &atts {
            println!(
                "  <{np}#claim> prov:wasGeneratedBy [ vela:verifierMethod {:?} ; vela:solverId {:?} ; vela:attachmentId {:?} ] ;",
                format!("{:?}", a.verifier_method),
                a.solver_id,
                a.id
            );
            println!(
                "    vela:replayCommand \"vela reproduce {}\" .",
                path.display()
            );
        }
        println!("}}");
        println!("<{np}#pubinfo> {{");
        println!(
            "  <{np}> prov:wasAttributedTo \"{}\" ; vela:frontier {:?} .",
            f.provenance
                .review
                .as_ref()
                .and_then(|r| r.reviewer.as_deref())
                .unwrap_or("unattributed"),
            project.frontier_id()
        );
        println!("}}");
        println!();
        emitted += 1;
    }
    eprintln!(
        "nanopub: emitted {emitted} TriG document(s) (findings with machine receipts or signed statement attestations)"
    );
}
