//! `vela agents sync|doctor|diff` — generate vendor agent-config adapters from
//! the canonical `VELA.md` (memo §5, §10). One source of truth; the adapter
//! files (`AGENTS.md`, `CLAUDE.md`, `.cursor/rules/vela.mdc`,
//! `.github/copilot-instructions.md`, `.mcp.json`) are disposable, regenerable
//! leaves. The deletion test holds: delete every adapter, run `agents sync`,
//! the same rules regenerate from VELA.md.

use crate::cli::{fail_return, print_json};
use crate::cli_commands::AgentsAction;
use serde_json::json;
use std::path::Path;

pub(crate) fn cmd_agents(action: AgentsAction) {
    match action {
        AgentsAction::Sync { root, json } => cmd_agents_sync(&root, json),
        AgentsAction::Doctor { root, json } => cmd_agents_doctor(&root, json),
        AgentsAction::Diff { root, json } => cmd_agents_diff(&root, json),
    }
}

const BEGIN: &str = "<!-- BEGIN GENERATED BY VELA. DO NOT EDIT DIRECTLY. -->";
const END: &str = "<!-- END GENERATED BY VELA. EDIT VELA.md AND RUN `vela agents sync`. -->";

/// The adapters generated from VELA.md, in deterministic order.
const TARGETS: &[&str] = &[
    "AGENTS.md",
    "CLAUDE.md",
    ".github/copilot-instructions.md",
    ".cursor/rules/vela.mdc",
    ".mcp.json",
];

struct Adapter {
    path: String,
    content: String,
}

/// Pull the body of a `## <heading>` section, up to the next `## ` heading.
fn extract_section(md: &str, heading: &str) -> Option<String> {
    let mut body: Vec<&str> = Vec::new();
    let mut in_section = false;
    for line in md.lines() {
        if in_section {
            if line.starts_with("## ") {
                break;
            }
            body.push(line);
        } else if line.trim() == heading {
            in_section = true;
        }
    }
    let joined = body.join("\n").trim().to_string();
    if joined.is_empty() {
        None
    } else {
        Some(joined)
    }
}

fn markdown_adapter(title: &str, rules: &str, commands: &str) -> String {
    format!(
        "{BEGIN}\n\
# {title}\n\n\
Generated from VELA.md. Do not edit here — edit VELA.md and run `vela agents sync`.\n\
VELA.md is the canonical, full agent charter for this worktree.\n\n\
## Agent rules\n\n{rules}\n\n\
## Fast commands\n\n{commands}\n\n\
See VELA.md for the full charter: hard rules, layout, contribution path, design, git.\n\
{END}\n"
    )
}

fn cursor_adapter(rules: &str) -> String {
    // Cursor `.mdc` rules. Kept short per memo §10.4; the canonical charter is
    // VELA.md. The frontmatter `alwaysApply` keeps the rule in context.
    format!(
        "---\ndescription: Vela frontier rules (generated from VELA.md)\nalwaysApply: true\n---\n\n\
{BEGIN}\n\
# Vela frontier rules\n\n\
Generated from VELA.md. Edit VELA.md and run `vela agents sync`; do not edit here.\n\n\
{rules}\n\n\
Use `vela status --json` before proposing changes. Every proposed transition is a\n\
draft until a key-holding human accepts it. The full charter is VELA.md.\n\
{END}\n"
    )
}

fn mcp_json_adapter(root: &Path) -> String {
    // Pick a serve invocation that actually loads in THIS worktree. A
    // single-frontier worktree (has `.vela/`) serves `.`; a multi-frontier
    // root serves its conventional frontiers directory (`frontiers/` per the
    // atlas layout, else `examples/`). `serve .` at a multi-frontier root, and
    // `serve --frontiers .` (which rescans non-frontier JSON), both fail.
    let args: Vec<String> = if root.join(".vela").is_dir() {
        ["serve", ".", "--profile", "read-only"]
            .iter()
            .map(|s| s.to_string())
            .collect()
    } else {
        let frontiers_dir = if root.join("frontiers").is_dir() {
            "frontiers"
        } else {
            "examples"
        };
        [
            "serve",
            "--frontiers",
            frontiers_dir,
            "--profile",
            "read-only",
        ]
        .iter()
        .map(|s| s.to_string())
        .collect()
    };
    let value = json!({
        "_generated_by": "vela agents sync (from VELA.md) — edit VELA.md, not this file",
        "mcpServers": {
            "vela-local": {
                "command": "vela",
                "args": args,
                "env": { "VELA_WORKTREE": "." }
            }
        }
    });
    let mut s = serde_json::to_string_pretty(&value).expect("serialize .mcp.json");
    s.push('\n');
    s
}

/// Build the full set of adapters from `<root>/VELA.md`. Fails loudly if VELA.md
/// is absent or missing the sections the adapters derive from.
fn build_adapters(root: &Path) -> Vec<Adapter> {
    let vela_md_path = root.join("VELA.md");
    let md = std::fs::read_to_string(&vela_md_path).unwrap_or_else(|_| {
        fail_return(&format!(
            "no VELA.md at {} — author the canonical agent charter first (it is the one source the adapters generate from; see the memo \u{00a7}5)",
            vela_md_path.display()
        ))
    });
    let rules = extract_section(&md, "## Agent rules").unwrap_or_else(|| {
        fail_return("VELA.md is missing a `## Agent rules` section (the adapters derive from it)")
    });
    let commands = extract_section(&md, "## Fast commands").unwrap_or_else(|| {
        fail_return("VELA.md is missing a `## Fast commands` section (the adapters derive from it)")
    });

    TARGETS
        .iter()
        .map(|&path| {
            let content = match path {
                "AGENTS.md" => markdown_adapter("Vela \u{2014} agent guide", &rules, &commands),
                "CLAUDE.md" => {
                    markdown_adapter("Vela \u{2014} Claude Code guide", &rules, &commands)
                }
                ".github/copilot-instructions.md" => {
                    markdown_adapter("Vela \u{2014} Copilot instructions", &rules, &commands)
                }
                ".cursor/rules/vela.mdc" => cursor_adapter(&rules),
                ".mcp.json" => mcp_json_adapter(root),
                other => fail_return(&format!("unknown adapter target {other}")),
            };
            Adapter {
                path: path.to_string(),
                content,
            }
        })
        .collect()
}

pub(crate) fn cmd_agents_sync(root: &Path, json_output: bool) {
    let adapters = build_adapters(root);
    let mut wrote: Vec<String> = Vec::new();
    let mut unchanged: Vec<String> = Vec::new();
    for a in &adapters {
        let target = root.join(&a.path);
        if let Some(parent) = target.parent() {
            std::fs::create_dir_all(parent)
                .unwrap_or_else(|e| fail_return(&format!("create dir for {}: {e}", a.path)));
        }
        let current = std::fs::read_to_string(&target).ok();
        if current.as_deref() == Some(a.content.as_str()) {
            unchanged.push(a.path.clone());
            continue;
        }
        std::fs::write(&target, &a.content)
            .unwrap_or_else(|e| fail_return(&format!("write {}: {e}", a.path)));
        wrote.push(a.path.clone());
    }
    if json_output {
        print_json(&json!({
            "command": "agents sync",
            "source": "VELA.md",
            "wrote": wrote,
            "unchanged": unchanged,
        }));
    } else {
        println!(
            "\u{00b7} agents sync: {} adapter(s) generated from VELA.md ({} written, {} already current)",
            adapters.len(),
            wrote.len(),
            unchanged.len()
        );
        for p in &wrote {
            println!("  wrote {p}");
        }
    }
}

/// Doctor / diff share the comparison core: which adapters are missing, drifted,
/// or in-sync against what `sync` would produce.
fn compare(root: &Path) -> (Vec<String>, Vec<String>, Vec<String>) {
    let adapters = build_adapters(root);
    let (mut missing, mut drifted, mut in_sync) = (Vec::new(), Vec::new(), Vec::new());
    for a in &adapters {
        match std::fs::read_to_string(root.join(&a.path)) {
            Err(_) => missing.push(a.path.clone()),
            Ok(c) if c == a.content => in_sync.push(a.path.clone()),
            Ok(_) => drifted.push(a.path.clone()),
        }
    }
    (in_sync, drifted, missing)
}

pub(crate) fn cmd_agents_doctor(root: &Path, json_output: bool) {
    let (in_sync, drifted, missing) = compare(root);
    let ok = drifted.is_empty() && missing.is_empty();
    if json_output {
        print_json(&json!({
            "command": "agents doctor",
            "ok": ok,
            "in_sync": in_sync,
            "drifted": drifted,
            "missing": missing,
        }));
    } else if ok {
        println!(
            "\u{00b7} agents doctor: ok \u{2014} all {} adapter(s) in sync with VELA.md",
            in_sync.len()
        );
    } else {
        println!("\u{00b7} agents doctor: out of sync with VELA.md");
        for p in &drifted {
            println!("  drifted {p} (run `vela agents sync`)");
        }
        for p in &missing {
            println!("  missing {p} (run `vela agents sync`)");
        }
    }
    if !ok {
        std::process::exit(1);
    }
}

pub(crate) fn cmd_agents_diff(root: &Path, json_output: bool) {
    let (in_sync, drifted, missing) = compare(root);
    let would_change: Vec<String> = drifted.iter().chain(missing.iter()).cloned().collect();
    if json_output {
        print_json(&json!({
            "command": "agents diff",
            "would_change": would_change,
            "in_sync": in_sync,
        }));
    } else if would_change.is_empty() {
        println!("\u{00b7} agents diff: nothing to change \u{2014} adapters match VELA.md");
    } else {
        println!(
            "\u{00b7} agents diff: {} adapter(s) would change on `vela agents sync`:",
            would_change.len()
        );
        for p in &would_change {
            println!("  {p}");
        }
    }
}
