pub mod access_tier;
pub mod adoption_log;
pub mod adoption_transcript;
pub mod agent_attestation;
pub mod agent_bench;
pub mod aggregate;
pub mod ancestor_closure;
pub mod artifact_audit;
pub mod artifact_to_state;
pub mod benchmark;
pub mod bridge;
pub mod bundle;
pub mod calibration;
pub mod canonical;
pub mod carina_validate;
pub mod causal_graph;
pub mod causal_reasoning;
pub mod checkpoint;
pub mod citation;
pub mod code_executor;
pub mod confidence;
pub mod conformance;
pub mod conjecture;
pub mod correction_return;
pub mod counterfactual;
pub mod credit;
pub mod crossref;
pub mod decision;
pub mod diff;
pub mod diff_pack_promote;
pub mod diff_pack_release;
pub mod diff_pack_review;
pub mod discord;
pub mod discord_compute;
pub mod doc_render;
pub mod doctor;
pub mod entity_resolve;
pub mod evaluation_record;
pub mod events;
pub mod evidence_ci;
pub mod merkle;
pub mod export;
pub mod contradiction;
pub mod federation;
pub mod nanopub;
pub mod frontier_controller;
pub mod frontier_graph;
pub mod frontier_health;
pub mod frontier_incident;
pub mod frontier_policy;
pub mod frontier_release;
pub mod frontier_repo;
pub mod frontier_task;
pub mod frontier_template;
pub mod governance;
pub mod hub_spec;
pub mod impact;
pub mod incremental_ingest;
pub mod index_db;
pub mod index_db_schema;
pub mod ingest;
pub mod lean_anchors;
pub mod lean_verification;
pub mod link;
pub mod lint;
pub mod normalize;
pub mod observer;
pub mod packet;
pub mod permission;
pub mod preprint;
pub mod project;
pub mod proof_packet;
pub mod proof_verification;
pub mod propagate;
pub mod proposals;
pub mod provenance_compute;
pub mod provenance_poly;
pub mod queue;
pub mod reducer;
pub mod registry;
pub mod released_diff_pack;
pub mod repo;
pub mod research_trace;
pub mod resolver;
pub mod retry;
pub mod review;
pub mod review_packet;
pub mod review_session;
pub mod review_thread;
pub mod review_thread_storage;
pub mod reviewer_identity;
pub mod runtime_adapters;
pub mod schema_registry;
pub mod scientific_diff;
pub mod search;
pub mod serve;
pub mod share_package;
pub mod sign;
pub mod signals;
pub mod source_adapters;
pub mod source_inbox;
pub mod source_resolver;
pub mod sources;
pub mod state;
pub mod state_integrity;
pub mod static_share;
pub mod status_provenance;
pub mod task_workspace;
pub mod tensions;
pub mod tool_descriptor;
pub mod tool_registry;
pub mod validate;
pub mod vela_agent_mcp;
pub mod verdict_conflict;
pub mod workbench;

pub mod cli;
mod cli_bridge_kit;
mod cli_causal;
mod cli_check;
mod cli_commands;
mod cli_diff_pack;
mod cli_federation;
mod cli_finding;
mod cli_frontier;
mod cli_lean;
mod cli_owner_rotate;
mod cli_registry;
mod cli_source_fetch;
pub mod cli_style;
